### ISSUE TITLE
c_hash check/consideration not being done in the library 

### ISSUE THREAD

**Issue by Lutando** [kalemontes/OIDCAndroidLib#11]
As per [spec](http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken) if you request a token using `code` instead of `access_token` you will get a `c_hash` instead of an `at_hash`. I beleive over [here](https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/java/com/lnikkila/oidc/OIDCRequestManager.java#L380) is where the code assumes only at_hash.

**Comment by kalemontes** [comment]
Actually i use [com.google.api.client.auth.openidconnect.IdTokenVerifier](https://developers.google.com/api-client-library/java/google-oauth-java-client/reference/1.19.0/com/google/api/client/auth/openidconnect/IdTokenVerifier) to verify the token (see [OIDCRequestManager.java#L632](https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/java/com/lnikkila/oidc/OIDCRequestManager.java#L632) ). I don't know the actual implémentation on this but i suppose it does both.

**Comment by Lutando** [comment]
youre right :)
