### ISSUE TITLE
missing variables

### ISSUE THREAD

**Issue by benjaminVadon** [kalemontes/OIDCAndroidLib#2]
Pulling from master, some variables in sample are missing. They was removed or renamed from the library in your last commits, but not all files where impacted by this change. Do they become useless for deleted var ?

APIUtility.java
-R.string.ACCOUNT_TYPE
                String accountType = context.getString(R.string.ACCOUNT_TYPE);

Config.java
-com.lnikkila.oidc.Config.Flows x2
        options.putString(AuthenticatorActivity.KEY_OPT_OIDC_CLIENT_FLOW_TYPE, com.lnikkila.oidc.Config.Flows.Hybrid.name());
-almost all KEY_OPT_OIDC_CLIENT_XXX 

HomeActivity.java
-R.string.ACCOUNT_TYPE  x2
        String accountType = getString(R.string.ACCOUNT_TYPE);
-com.lnikkila.oidc.Config.userInfoUrl
       return APIUtility.getJson(HomeActivity.this, com.lnikkila.oidc.Config.userInfoUrl, account, options, accountCallBack);

**Comment by kalemontes** [comment]
I forgot to update the sample. I'll be pushing the changes really soon (1h or so).

**Comment by kalemontes** [comment]
I pushed the changes but didn't have the time to check if all works as expected. I'll do some checks tonight and let u know.

**Comment by juanifioren** [comment]
Works for me :)
