### ISSUE TITLE
Gradle Project Sync Failed

### ISSUE THREAD

**Issue by juanifioren** [kalemontes/OIDCAndroidLib#3]
Sorry, am just trying to run the client example but don't know Android (Java neither).
Getting an error when import the project.

![screenshot from 2015-11-12 12 58 17](https://cloud.githubusercontent.com/assets/5168681/11123365/168ecc26-893e-11e5-8ab3-ed77e9f171c5.png)

What am I doing wrong?? Thanks.

**Comment by kalemontes** [comment]
Check the console log, it should tell you what's wrong. Usually it's the buildtoolsversion (update the gradle file to match yours) you don't have the SDK 22 (matched it with your latest SDK or download the SDK 22 from the SDK manager).

**Comment by juanifioren** [comment]
@kalemontes It works but can't find the file `Config.java`. Where I set my **clientId** and **clientSecret**?.

Greetings.

**Comment by kalemontes** [comment]
There's no more Config.java. Oidc client configuration and endpoint configuration is done in the XML string files on "res/values/oidc_*".

**Comment by kalemontes** [comment]
The idea on migrating the configuration to string files is to be able to overwrite the default configuration without touching the lib, and hopefully soon be able to deploy an aar lib to make it easier to integrate with gradle.

**Comment by juanifioren** [comment]
It works @kalemontes . Thanks for the support. Awesome lib
