### ISSUE TITLE
Distribute the library through jCenter 

### ISSUE THREAD

**Issue by kalemontes** [kalemontes/OIDCAndroidLib#8]
It would be nice to have a simple gradle configuration like `compile 'com.kalemontes.oidc:openidconnect-android-client:x.x.x'` to add dependency to project.

**Comment by asinel** [comment]
Any updates?

**Comment by kalemontes** [comment]
Hi, actually yes. I've been busy with other proyects but if you look at the dev branch you should find the info you are looking for : https://github.com/kalemontes/OIDCAndroidLib/tree/dev . I haven't had the time to test thoses changes correctly and that's why i haven't merge them with the master branch.

**Comment by asinel** [comment]
I have asked about jcenter

**Comment by asinel** [comment]
Also I have no idea how to use it, because wiki is empty

**Comment by kalemontes** [comment]
I don't think the wiki is empty. There's a pages menu on the right.

**Comment by asinel** [comment]
@kalemontes yes, but only menu. When you click on any page, it says "TODO".
For example: https://github.com/kalemontes/OIDCAndroidLib/wiki/2.1.-Configure-endpoins

**Comment by kalemontes** [comment]
You are right, i didn't end the wiki. I'll be working soon on this proyect once more so i'll complete it some time soon. For now you can check the sample App + the configure instruction on https://github.com/kalemontes/OIDCAndroidLib/tree/dev#configuration .

The configuration file are actually : 

https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/res/values/oidc_endpoints.xml

https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/res/values/oidc_clientconf.xml

https://github.com/kalemontes/OIDCAndroidLib/blob/master/oidclib/src/main/res/values/oidc_clientoptions.xml

You have to add them to your values folder and adapt them to your needs.

Am gonna open a new issue because what we are discussing here has nothing to do with this issue.
